# Generated by Django 3.0.7 on 2020-06-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='status',
        ),
        migrations.AddField(
            model_name='process',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
