# Generated by Django 3.0.7 on 2020-06-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20200627_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='initiated',
            field=models.BooleanField(default=False),
        ),
    ]
